DELETE FROM sqldados.engecopi_tef_bruto WHERE NSU = :NSU;

INSERT INTO sqldados.engecopi_tef_bruto(NSU, TIPO, STATUS, CODIGOLOJA, NOMELOJA, PEDIDO, VALOR,
					DATACRIACAO, DATAEFETIVACAO, DATAEFETIVACAOOSITEF,
					IDAUTORIZADORA, NOMEAUTORIZADORA, TIPOPAGAMENTO,
					RESPOSTASITEF, MENSAGEMSITEF, NSUSITEF, NSUHOST, NSULOJA,
					AUTORIZACAO, PARCELAS, FINANCIAMENTO, TID, ECI, ESTILO,
					AVISOS, FALHAS, AVISADA, IPCLIENTE, DOCUMENTO, MOEDA)
VALUES (:NSU, :TIPO, :STATUS, :CODIGOLOJA, :NOMELOJA, :PEDIDO, :VALOR, :DATACRIACAO,
        :DATAEFETIVACAO, :DATAEFETIVACAOOSITEF, :IDAUTORIZADORA, :NOMEAUTORIZADORA, :TIPOPAGAMENTO,
	:RESPOSTASITEF, :MENSAGEMSITEF, :NSUSITEF, :NSUHOST, :NSULOJA, :AUTORIZACAO, :PARCELAS,
	:FINANCIAMENTO, :TID, :ECI, :ESTILO, :AVISOS, :FALHAS, :AVISADA, :IPCLIENTE, :DOCUMENTO,
	:MOEDA)